# Site Info
title: song's blog
tagline: 'NLP'
description: 'blog'
url: http://songys.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: song
  description: <strong>오늘 하루</strong>
  gravatar:  288B6CF34E4C65E928B2C15563277FF6 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/%EC%98%81%EC%88%99-%EC%86%A1-768491b0//
    github:    https://github.com/songys
    facebook:  https://www.facebook.com/youngsook.song.1
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:klaguage1004@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://songys.github.io/public/img/picture.JPG
  caption: Good Luck
# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'songys-github-io' # leave blank if you don't want disqus

